[package]
name = "juno-rs"
version = "0.3.0"
authors = ["Jaanus Varus <jaanusvarus@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "juno_rs/lib.rs"

[dependencies]
paste = "0.1.6"
