[package]
name = "juno-rs"
version = "0.5.0"
authors = ["Jaanus Varus <jaanusvarus@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "juno_rs/lib.rs"

[dependencies]
ndarray = "0.13"
ndarray-stats = "0.3"
