[package]
name = "juno-rs"
version = "0.1.0"
authors = ["Jaanus Varus <jaanusvarus@gmail.com>"]
edition = "2018"

[lib]
name = "juno_rs"
crate-type = ["cdylib"]

[dependencies]
circular-queue = "0.2.1"
pyo3 = { version = "0.7.0", features = ["extension-module"] }
rust_decimal = "1.0.2"
