[package]
name = "juno_bin_rs"
version = "0.1.0"
authors = ["discosultan <jaanusvarus@gmail.com>"]
edition = "2018"

[dependencies]
juno_rs = { version = "0.1", path = "../juno_rs" }
prettytable-rs = "0.8"
